<?php

namespace Kr\OAuthServerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AuthorizationCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorizationCodeRepository extends EntityRepository
{
}
